Backend for Graph 4: Top 3 popular Cuisine Types by Area
bcfoodapp/streetfoodlove pull request #441
Opened 2022-05-21 07:43 UTC by silviacasaburi

2022-05-21 07:46 UTC, silviacasaburi commented
Backend for Graph 4: Top 3 popular Cuisine Types by Area

2022-05-22 04:03 UTC, MakotoE requested changes
The package-lock.json file is unnecessary but you added it in this PR. Please remove that file.

2022-05-22 04:03 UTC, MakotoE commented on backend/database/database.go
> +					count(distinct(StarRating)) as "TotalRating"
You have a `TotalRatings` field in `AreaByRating`, so you should change the above column name to match that.

2022-05-23 09:17 UTC, silviacasaburi commented
Hi Makoto, I just added  Graph 3: Top 5 Popular Searching Queries in a certain month, to the backend. Can you please review?

Thank you,
Silvia

2022-05-23 16:18 UTC, MakotoE requested changes
You deleted app/package-lock.json which is the one that needs to be kept.

2022-05-24 04:53 UTC, MakotoE requested changes

2022-05-24 04:53 UTC, MakotoE commented on backend/database/database.go
> +inner join reviews ON CuisineTypes.VendorID = Reviews.VendorID
Please change `reviews` to `Reviews`.

2022-05-24 15:33 UTC, MakotoE approved these changes

2022-05-24 15:33 UTC, merged